### ISSUE TITLE
Может в masterclass.js переименовать owner в master, а participent в students?

### ISSUE THREAD

**Issue by kicumkicum** [nomean42/summer-camp-timetable-planner#25]

**Comment by nomean42** [comment]
согласен, так будет и яснее и короче

**Comment by kicumkicum** [comment]
А это где то уже переименовано?

**Comment by nomean42** [comment]
да, прямо в девелопе, правда он немного локален )

**Comment by kicumkicum** [comment]
test test test

2015-10-09 23:23 GMT+06:00 Igor Goryaynov notifications@github.com:

**Comment by kicumkicum** [comment]
прикольно. можно отвечать прямо в почте :)

2015-10-12 10:51 GMT+06:00 oleg akinin kicumkicum@gmail.com:

**Comment by nomean42** [comment]
угарно, я попробую
